### ISSUE TITLE
System remove, ##remove not known in module

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#720]
I'm getting the following message when trying to test a new version of SRFI 179, which uses the system `remove`, when trying to run it as a module:
```
*** ERROR IN #<procedure #20>, "srfi/179/generic-arrays.scm"@3883.36 -- Unbound variable: srfi/179#remove
```
I thought the following might fix it, but no luck:
```
heine:~/programs/gambit/gambit> git diff
diff --git a/lib/gambit/prim/list-gambit#.scm b/lib/gambit/prim/list-gambit#.scm
index f981f0ee..7dad466a 100644
--- a/lib/gambit/prim/list-gambit#.scm
+++ b/lib/gambit/prim/list-gambit#.scm
@@ -28,6 +28,7 @@ list-sort
 list-sort!
 list-tabulate
 proper-list?
+remove
 reverse!
 take
 xcons
diff --git a/lib/gambit/prim/list.sld b/lib/gambit/prim/list.sld
index 295420c7..fbcaa67e 100644
--- a/lib/gambit/prim/list.sld
+++ b/lib/gambit/prim/list.sld
@@ -93,6 +93,7 @@ list-sort
 list-sort!
 list-tabulate
 proper-list?
+remove
 reverse!
 take
 xcons
diff --git a/lib/gambit/prim/prim.sld b/lib/gambit/prim/prim.sld
index 4ff06abf..a7e5aa53 100644
--- a/lib/gambit/prim/prim.sld
+++ b/lib/gambit/prim/prim.sld
@@ -529,6 +529,7 @@ last
 last-pair
 list-set
 list-tabulate
+remove
 reverse!
 take
 xcons
```
Now I'm deep in the bowels of `gsc/_prims.scm` but I don't understand what all the entries of the prims list mean.

This must be a quick fix, can you help?

**Comment by feeley** [comment]
ebfe461af2057feda99bb80888f6fe4ae40d17cf should fix it.

**Comment by gambiteer** [comment]
Still the same.

**Comment by gambiteer** [comment]
Here's what the procedure expansion looks like:
```
1> ,i
#<procedure #20> =
(lambda (storage-class mutable? safe?)
  (let ((domain (srfi/179#%%array-domain first-array)))
    (let ((domain-dimension (srfi/179#%%interval-dimension domain)))
      (let ((lowers (srfi/179#%%interval-lower-bounds->list domain)))
        (let ((uppers (srfi/179#%%interval-upper-bounds->list domain)))
          (let ((result-dimension (fx+ 1 domain-dimension)))
            (let ((result-domain
                   (srfi/179#%%finish-interval
                    (list->vector (append (take lowers k) (cons 0 (drop lowers k))))
                    (list->vector (append (take uppers k) (cons number-of-arrays (drop uppers k)))))))
              (let ((result-array (srfi/179#%%make-specialized-array result-domain storage-class (srfi/179#storage-class-default storage-class) safe?)))
                (let ((permutation (list->vector (cons k (srfi/179#remove (lambda (i) (fx= i k)) (iota result-dimension)))))) ;;; <<<<
                  (let ((permuted-and-curried-result (srfi/179#%%array-curry (srfi/179#%%array-permute result-array permutation) domain-dimension)))
                    (srfi/179#array-for-each
                     (lambda (destination source) (srfi/179#%%move-array-elements destination source "array-stack!: "))
                     permuted-and-curried-result
                     (srfi/179#list->array arrays (srfi/179#make-interval (vector number-of-arrays))))
                    (if (not mutable?) (srfi/179#%%array-setter-set! result-array #f))
                    result-array))))))))))
```

**Comment by gambiteer** [comment]
I've tried a few more things, here's what I have now:
```
heine:~/programs/gambit/gambit> git diff
diff --git a/gsc/_prims.scm b/gsc/_prims.scm
index 2bff43ed..ea584079 100644
--- a/gsc/_prims.scm
+++ b/gsc/_prims.scm
@@ -658,6 +658,8 @@
 ("##cons*"                            1     #f ()    0    #f      extended)
 ("drop"                               (2)   #f 0     0    list    gambit)
 ("##drop"                             (2)   #f ()    0    list    extended)
+("filter"                             (2)   #f 0     0    list    gambit)
+("##filter"                           (2)   #f ()    0    list    extended)
 ("fold"                               3     #t (1 . 3) 0  (#f)    gambit)
 ("##fold"                             3     #t ()    0    (#f)    extended)
 ("fold-right"                         3     #t (1 . 3) 0  (#f)    gambit)
@@ -672,6 +674,8 @@
 ("##list-set"                         (3)   #f ()    0    pair    extended)
 ("list-tabulate"                      (2)   #t 0     0    list    gambit)
 ("##list-tabulate"                    (2)   #t ()    0    list    extended)
+("remove"                             (2)   #f 0     0    list    gambit)
+("##remove"                           (2)   #f ()    0    list    extended)
 ("reverse!"                           (1)   #t 0     0    list    gambit)
 ("##reverse!"                         (1)   #t ()    0    list    extended)
 ("take"                               (2)   #f 0     0    list    gambit)
@@ -2030,6 +2034,7 @@
 (def-spec "circular-list"      (spec-s "##circular-list"))
 (def-spec "cons*"              (spec-s "##cons*"))
 (def-spec "drop"               (spec-u "##drop"))
+(def-spec "filter"             (spec-u "##filter"))
 (def-spec "fold"               (spec-u "##fold"))
 (def-spec "fold-right"         (spec-u "##fold-right"))
 (def-spec "iota"               (spec-u "##iota"))
@@ -2037,6 +2042,7 @@
 (def-spec "last-pair"          (spec-u "##last-pair"))
 (def-spec "list-set"           (spec-u "##list-set"))
 (def-spec "list-tabulate"      (spec-u "##list-tabulate"))
+(def-spec "remove"             (spec-u "##remove"))
 (def-spec "reverse!"           (spec-u "##reverse!"))
 (def-spec "take"               (spec-u "##take"))
 (def-spec "xcons"              (spec-s "##xcons"))
diff --git a/lib/gambit/prim/list.sld b/lib/gambit/prim/list.sld
index 295420c7..96bf8653 100644
--- a/lib/gambit/prim/list.sld
+++ b/lib/gambit/prim/list.sld
@@ -82,6 +82,7 @@ circular-list?
 cons*
 dotted-list?
 drop
+filter
 fold
 fold-right
 iota
@@ -93,6 +94,7 @@ list-sort
 list-sort!
 list-tabulate
 proper-list?
+remove
 reverse!
 take
 xcons
diff --git a/lib/gambit/prim/prim.sld b/lib/gambit/prim/prim.sld
index 4ff06abf..194c4458 100644
--- a/lib/gambit/prim/prim.sld
+++ b/lib/gambit/prim/prim.sld
@@ -522,6 +522,7 @@ list-set!
 circular-list
 cons*
 drop
+filter
 fold
 fold-right
 iota
@@ -529,6 +530,7 @@ last
 last-pair
 list-set
 list-tabulate
+remove
 reverse!
 take
 xcons
```
Perhaps you can document what you mean by "strictness pattern" and "lift pattern" in `_prims.scm`, I just used the "copy-and-paste" method of programming there.

But the problem persists, here is a slightly better-formatted version of the problem code:
```
*** ERROR IN #<procedure #20>, "srfi/179/generic-arrays.scm"@3883.36 -- Unbound variable: srfi/179#remove
1> ,i
#<procedure #20> =
(lambda (storage-class mutable? safe?)
  (let ((domain (srfi/179#%%array-domain first-array)))
    (let ((domain-dimension (srfi/179#%%interval-dimension domain)))
      (let ((lowers (srfi/179#%%interval-lower-bounds->list domain)))
        (let ((uppers (srfi/179#%%interval-upper-bounds->list domain)))
          (let ((result-dimension (fx+ 1 domain-dimension)))
            (let ((result-domain
                   (srfi/179#%%finish-interval
                    (list->vector (append (take lowers k) (cons 0 (drop lowers k))))
                    (list->vector
                     (append (take uppers k) (cons number-of-arrays (drop uppers k)))))))
              (let ((result-array
                     (srfi/179#%%make-specialized-array
                      result-domain
                      storage-class
                      (srfi/179#storage-class-default storage-class)
                      safe?)))
                (let ((permutation
                       (list->vector
                        (cons k
                              (srfi/179#remove      ;; <<<<<<<<<<<<<<<<<<< Problem
                               (lambda (i) (fx= i k))
                               (iota result-dimension))))))
                  (let ((permuted-and-curried-result
                         (srfi/179#%%array-curry
                          (srfi/179#%%array-permute result-array permutation)
                          domain-dimension)))
                    (srfi/179#array-for-each
                     (lambda (destination source)
                       (srfi/179#%%move-array-elements destination source "array-stack!: "))
                     permuted-and-curried-result
                     (srfi/179#list->array
                      arrays
                      (srfi/179#make-interval (vector number-of-arrays))))
                    (if (not mutable?) (srfi/179#%%array-setter-set! result-array #f))
                    result-array))))))))))
1> 
```

**Comment by feeley** [comment]
It is the rest of the code that is interesting (specifically any `namespace` declaration)...

**Comment by gambiteer** [comment]
Here's `srfi/179/179.sld`:
```
(define-library (srfi 179)
  (export
    ;; Miscellaneous Functions
    translation? permutation?

    ;; Intervals
    make-interval interval? interval-dimension interval-lower-bound interval-upper-bound interval-lower-bounds->list interval-upper-bounds->list
    interval-lower-bounds->vector interval-upper-bounds->vector interval= interval-volume interval-subset? interval-contains-multi-index?
    interval-projections interval-for-each interval-dilate interval-intersect interval-translate interval-permute interval-rotate interval-scale
    interval-cartesian-product

    ;; Storage Classes
    make-storage-class storage-class? storage-class-getter storage-class-setter storage-class-checker storage-class-maker storage-class-copier
    storage-class-length storage-class-default generic-storage-class s8-storage-class s16-storage-class s32-storage-class s64-storage-class
    u1-storage-class u8-storage-class u16-storage-class u32-storage-class u64-storage-class f8-storage-class f16-storage-class f32-storage-class
    f64-storage-class c64-storage-class c128-storage-class

    ;; Arrays
    make-array array? array-domain array-getter array-dimension mutable-array? array-setter specialized-array-default-safe?
    specialized-array-default-mutable? make-specialized-array specialized-array? array-storage-class array-indexer array-body array-safe?
    array-elements-in-order? specialized-array-share array-copy array-curry array-extract array-tile array-translate array-permute
    array-rotate array-reverse array-sample array-outer-product array-inner-product array-map array-for-each array-foldl array-foldr array-reduce array-any array-every
    array->list list->array array-assign! array-append array-stack specialized-array-reshape array-ref array-set!
    )

  (cond-expand
    (gambit
     (import (gambit)))
    (else
     (import (scheme base))))

  (include "generic-arrays.scm"))
```
Here's what seems to be relevant to `test-arrays.scm`:
```
(begin
  ;; To run test-arrays.scm as an R7RS module in Gambit,
  ;; take the following steps:
  ;; 1. Put generic-arrays.scm and 179.sld in new directory ./srfi/179.
  ;; 2. Uncomment this "begin".
  ;; 3. Run "gsi . test-arrays".
  
  (import (srfi 179))
  
  (##namespace
   ("srfi/179#"
    ;; Internal SRFI 179 procedures that are either tested or called here.
    %%compose-indexers
    make-%%array
    %%every
    %%interval->basic-indexer
    %%interval-lower-bounds
    %%interval-upper-bounds
    %%move-array-elements
    %%permutation-invert
    %%vector-every
    %%vector-permute
    %%vector-permute->list
    %%order-unknown
    %%compute-array-elements-in-order?
    %%array-domain
    %%array-indexer
    %%array-getter
    %%array-elements-in-order?))
  )
```
I don't see any declarations in `generic-arrays.scm` that might seem relevant.

**Comment by gambiteer** [comment]
`remove` isn't in `lib/gambit/gambit.sld`.  I'll add it to my other changes and see whether things work.

**Comment by gambiteer** [comment]
You already caught it, thanks.

What about my changes to the other files?

**Comment by feeley** [comment]
Before fix:

```
> (let () (##namespace ("foo#") ("" pp lambda import)) (pp (lambda () (import (gambit)) remove filter remq drop cons)))               
(lambda () foo#remove foo#filter foo#remq drop cons)
```

After fix:

```
> (let () (##namespace ("foo#") ("" pp lambda import)) (pp (lambda () (import (gambit)) remove filter remq drop cons)))               
(lambda () remove filter remq drop cons)
```

**Comment by feeley** [comment]
The other changes are not needed and there's no point adding non-inlined primitives to `_prim.scm`.

**Comment by gambiteer** [comment]
Re: There's no point adding non-inlined primitives to `_prims.scm`.

How does the compiler know to replace a call to `remove` by a call to `##remove`?  Isn't that a `def-spec` or something in `_prims.scm`?
