### ISSUE TITLE
Difficult to reproduce `make` write error

### ISSUE THREAD

**Issue by belmarca** [gambit/gambit#833]
I encounter a difficult to reproduce `make` error on recent builds:

```
make[1]: write error: stdout
make: *** [makefile:543: core-recursive] Error 1
```

This seems to be indicative of an eagerly closed port to which `make` was writing. This issue appears after commit `77c2da5192facf5b057584cbf7e4d8b1725a8c1c`. Commit `5703cd7d956832fc73549f29e99a80358f0a517d` and later can emit a potentially large amount of text to `stdout`. I cannot reproduce the error reliably except on commit `77c2da5192facf5b057584cbf7e4d8b1725a8c1c`.

**Comment by fare** [comment]
77c2da compiles fine for me, but 5703cd7 doesn't. The commit adds some warnings. Maybe warnings are now being written during some build or test step while the stderr is closed, causing havoc?

**Comment by gambiteer** [comment]
I’m wondering whether stdout should be flushed after each warning message. Perhaps the port is being closed before all the warnings have printed in a parallel build.

**Comment by fare** [comment]
My best theory so far:
As per https://www.gnu.org/software/make/manual/html_node/Parallel-Input.html only one of the parallel processes at a time has access to stdin, depending on which starts first after the previous that did died. If that process issues one of the new warnings from commit 5703cd7, gambit somehow detects that its stdin is a console, and tries it for output, too, and miserably fails, breaking the build.

Proposed fixes, if confirmed: either a better console detection if possible, or disabling the warnings somehow, or explicitly redirecting input and/or output during the making of the bad actions. All of it easier said than done.

**Comment by feeley** [comment]
Very interesting! I'll explore this lead some more.

**Comment by feeley** [comment]
The Gambit runtime system does I/O using nonblocking file descriptors. This is so that `select` can be used to manage I/O performed by several Scheme threads without blocking the threads. In particular the stdin/stdout need to be put in nonblocking mode, which is done with `fcntl`. Moreover, the runtime system needs to set the terminal settings with `tcsetattr` to implement a `readline` feature (to remove echo which is done by the readline implementation).

To "play well" with the user's environment the terminal settings and nonblocking flag are read when the runtime system is setup, and then the terminal settings and nonblocking flag are set to remove echo and do nonblocking I/O, and at the end of execution the initial terminal settings and nonblocking flag are reinstated.

Unfortunately, this doesn't work well when several programs are run in parallel. Say there are two programs P1 and P2, and P1 starts before P2 starts, P2 starts before P2 ends, and P1 ends before P2 ends. Then at the end of this sequence the stdin/stdout will be in nonblocking mode because when P2 started it observed that stdin/stdout were in nonblocking mode.

I conjecture that this is a problem for `make` because it is using the same stdout file descriptor for displaying its messages, and when it tries to write to the stdout file descriptor it gets an incomplete write, which is unexpected for `make`, leading to `make` displaying a `write error` message. It is not clear if this is a bug in `make` (the spec isn't very clear on parallel execution) but it would make sense for `make` to use a defensive approach and tolerate executing programs that change the blocking flag of stdin/stdout.

To solve this issue the runtime system has been changed to always set the stdin/stdout back to blocking mode when the program exits, regardless of the blocking mode when the program started.

**Comment by gambiteer** [comment]
I still see the bug.

**Comment by feeley** [comment]
During the building of Gambit in `boot` or after the bootstrap? The build in `boot` will still have the issue because the runtime system in that build is the one of the last release, which has the bug when `make -jN` is used.

In principle this should work from a `git clone`:

```
$ ./configure --enable-single-host
$ make core   # no -jN used here
$ make bootstrap   # replace gsc-boot with gsc/gsc
$ make bootclean
$ make -j8
```

If it does please close this issue since it will be fully resolved at the next release.

**Comment by gambiteer** [comment]
The following series of commands gave me the error:
```
   142	9:46	git pull
   144	9:46	./configure '--enable-march=native' '--enable-dynamic-clib' '--enable-single-host' '--enable-multiple-versions' '--enable-shared'
   145	9:46	update-gambit-git                  <<<<<<< This failed
   146	9:52	update-gambit-git                 <<<<<<<< This didn't fail
   147	11:43	make bootstrap            <<<<<<<< Try to do what you suggest
   148	11:44	make bootclean
   149	11:44	make -j8                       <<<<<<<< This failed building gcc
```
with
```
heine:~/programs/gambit/gambit> cat `which update-gambit-git`
#git pull & rm -rf * & git checkout -- .

make clean\
&& rm -rf boot gsc-boot\
&& git pull\
&& make -j8 core\
&& make -j8 modules\
&& make doc\
&& make check
```

**Comment by feeley** [comment]
The following was tested to work fine on a debian linux machine:

```
$ git clone git@github.com:gambit/gambit
$  cd gambit
$ ./configure --enable-single-host
$  make core
$ make bootstrap
$ make bootclean
$ make -j8
$ make check
```

I'm not sure what is the issue on your end.

**Comment by gambiteer** [comment]
OK, when I do it your way, as
```
   157	13:00	git clone https://github.com/gambit/gambit.git
   158	13:01	cd gambit
   159	13:01	./configure --enable-single-host
   160	13:01	make core
   161	13:13	make bootstrap
   162	13:13	make bootclean
   163	13:14	make -j8 core
   164	13:16	make bootclean
   165	13:16	make -j8 core
```
I get no failures, but also I see no warnings like
```
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/../gsc/_envadt.scm"@16.54 -- "c#next-var-stamp" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/../gsc/_gvmadt.scm"@37.38 -- "c#enter-opnd" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/../gsc/_gvmadt.scm"@34.39 -- "c#*opnd-table*" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/../gsc/_ptreeadt.scm"@75.54 -- "c#next-node-stamp" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@168.8 -- "c#compiler-internal-error" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@271.8 -- "c#compiler-error" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@291.15 -- "c#prim-procs" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@295.16 -- "c#string->canonical-symbol" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@298.24 -- "c#make-proc-obj" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@338.34 -- "c#return-addr-reg" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@340.8 -- "c#make-pcontext" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@401.12 -- "c#append-lists" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@411.4 -- "c#setup-prims" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@426.27 -- "c#**dead-end-sym" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@429.27 -- "c#**identity-sym" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@432.27 -- "c#**not-sym" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@435.27 -- "c#**eq?-sym" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@438.27 -- "c#**quasi-append-sym" is not defined
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_back.scm"@441.27 -- "c#**quasi-list-sym" is not defined
```
It's when these warnings are printed that there are intermittent parallel build errors.
I don't know why I don't get these warnings when I follow these instructions.

So:
(a) Did you fix the code so these warnings aren't issued?
(b) Are you building a `gsc-boot` that produces these warnings when appropriate?

**Comment by feeley** [comment]
I fixed the `write error` issue in commit 420f1e5e76661ea9fff2e0b5c71363d91a23ca04. After that I fixed the undefined references in the Gambit compiler's source code in commit cfa29b03248a1eaea81675ce541fd810f32860d0. So if you want to test that the `write error` issue has been fixed you need to checkout 420f1e5e76661ea9fff2e0b5c71363d91a23ca04.

Those warnings were not errors. The Gambit compiler's source code was correct but the compiler was unsure whether the references were to undefined global variables or not, so it issued a warning. Now I have added `namespace` declarations that allow the compiler to know the references are OK.

Moving forward I think these warnings should be on by default in order to catch undefined references early. It has already helped to find a few (minor) errors.

**Comment by gambiteer** [comment]
OK, I think I understand now.  If I do
```
   220	16:59	git clone https://github.com/gambit/gambit.git
   221	17:00	cd gambit
   223	17:00	./configure '--enable-march=native' '--enable-dynamic-clib' '--enable-single-host' '--enable-multiple-versions' '--enable-shared'
   224	17:01	make -j8
   225	17:10	make check
   226	17:10	make test-modules
   227	17:20	make -j doc
```
which is a reasonable facsimile to the instructions on the Gambit github README, then
1.  You fixed `gsc/*.scm` so gsc-boot doesn't give hundreds of warnings.
2. `gsc-boot` does not have the `write error` fix, while `gsc/gsc` does.  (This doesn't matter much any more because the hundreds of warnings were fixed.)
3. `make test-modules` still fails for unknown reasons.
and 2 and 3 will be fixed by releasing the next release.
So I think it's time for the next release.
